{
  "openapi": "3.1.0",
  "info": {
    "title": "API",
    "version": "1.0.0",
    "description": "Docs"
  },
  "servers": [
    {
      "url": "http://localhost:8000/api/v1"
    }
  ],
  "paths": {
    "/auth/login": {
      "parameters": [],
      "post": {
        "tags": [
          "Auth"
        ],
        "summary": "Login",
        "security": [],
        "parameters": [],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "token": {
                      "type": "string"
                    }
                  }
                },
                "example": {
                  "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMDAvYXBpL3YxL2F1dGgvbG9naW4iLCJpYXQiOjE3NTY4MTgzODEsImV4cCI6MTc1NjgyMTk4MSwibmJmIjoxNzU2ODE4MzgxLCJqdGkiOiJ3bkgwczF0SGN4WjJVUjMwIiwic3ViIjoiMSIsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.sBLuWEKiPaSb7xVpHIiH05lrDde5TVqg6Ok9pU0BhuQ"
                }
              }
            }
          },
          "401": {
            "description": "Credentials Do Not Match",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "string",
                      "format": "style"
                    }
                  }
                },
                "example": {
                  "error": "Login failed: These credentials do not match our records."
                }
              }
            }
          },
          "422": {
            "description": "Unprocessable Content",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "string"
                    },
                    "errors": {
                      "type": "object",
                      "properties": {
                        "email": {
                          "type": "array",
                          "items": {
                            "type": "string"
                          }
                        },
                        "password": {
                          "type": "array",
                          "items": {
                            "type": "string"
                          }
                        }
                      }
                    }
                  }
                },
                "example": {
                  "error": "The email field is required. (and 1 more error)",
                  "errors": {
                    "email": [
                      "The email field is required."
                    ],
                    "password": [
                      "The password field is required."
                    ]
                  }
                }
              }
            }
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "email": {
                    "type": "string",
                    "format": "email"
                  },
                  "password": {
                    "type": "string"
                  }
                }
              },
              "example": {
                "email": "admin@example.com",
                "password": "admin"
              }
            }
          }
        }
      }
    },
    "/auth/logout": {
      "parameters": [],
      "post": {
        "tags": [
          "Auth"
        ],
        "summary": "Logout",
        "parameters": [],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  }
                },
                "example": {
                  "message": "Logged out successfully"
                }
              }
            }
          },
          "500": {
            "description": "Invalid Token",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "string"
                    }
                  }
                },
                "example": {
                  "error": "Token could not be parsed from the request."
                }
              }
            }
          }
        }
      }
    },
    "/auth/register": {
      "parameters": [],
      "post": {
        "tags": [
          "Auth"
        ],
        "summary": "Register",
        "parameters": [],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "token": {
                      "type": "string"
                    }
                  }
                },
                "example": {
                  "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMDAvYXBpL3YxL2F1dGgvcmVnaXN0ZXIiLCJpYXQiOjE3NTY4MjY0NDgsImV4cCI6MTc1NjgzMDA0OCwibmJmIjoxNzU2ODI2NDQ4LCJqdGkiOiI5SVBsYlR4Z3Z3eGxteHFIIiwic3ViIjoiMiIsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.ymQTAatRYSg_PoFebSlkM-eHo9wSGuxo0yzBFDctddU"
                }
              }
            }
          },
          "422": {
            "description": "Unprocessable Content",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "string"
                    },
                    "errors": {
                      "type": "object",
                      "properties": {
                        "name": {
                          "type": "array",
                          "items": {
                            "type": "string"
                          }
                        },
                        "email": {
                          "type": "array",
                          "items": {
                            "type": "string"
                          }
                        },
                        "password": {
                          "type": "array",
                          "items": {
                            "type": "string"
                          }
                        }
                      }
                    }
                  }
                },
                "example": {
                  "error": "The name field is required. (and 2 more errors)",
                  "errors": {
                    "name": [
                      "The name field is required."
                    ],
                    "email": [
                      "The email field is required."
                    ],
                    "password": [
                      "The password field is required."
                    ]
                  }
                }
              }
            }
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string"
                  },
                  "email": {
                    "type": "string",
                    "format": "email"
                  },
                  "password": {
                    "type": "string"
                  },
                  "password_confirmation": {
                    "type": "string"
                  }
                }
              },
              "example": {
                "name": "Teste",
                "email": "teste@teste.gmail.com",
                "password": "teste123",
                "password_confirmation": "teste123"
              }
            }
          }
        }
      }
    },
    "/auth/active-role": {
      "parameters": [],
      "post": {
        "tags": [
          "Auth"
        ],
        "summary": "Set User Active Role",
        "parameters": [],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "integer"
                    },
                    "name": {
                      "type": "string"
                    },
                    "email": {
                      "type": "string",
                      "format": "email"
                    },
                    "active_role": {
                      "type": "string"
                    },
                    "roles": {
                      "type": "array",
                      "items": {
                        "type": "string"
                      }
                    },
                    "permissions": {
                      "type": "array",
                      "items": {
                        "type": "string"
                      }
                    }
                  }
                },
                "example": {
                  "id": 1,
                  "name": "Admin",
                  "email": "admin@example.com",
                  "active_role": "admin",
                  "roles": [
                    "admin",
                    "user"
                  ],
                  "permissions": [
                    "user.create",
                    "user.read",
                    "user.update",
                    "user.delete",
                    "user.assign.role",
                    "user.revoke.role",
                    "user.sync.role",
                    "country.create",
                    "country.read",
                    "country.update",
                    "country.delete",
                    "state.create",
                    "state.read",
                    "state.update",
                    "state.delete",
                    "city.create",
                    "city.read",
                    "city.update",
                    "city.delete"
                  ]
                }
              }
            }
          },
          "422": {
            "description": "Unprocessable Content",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "string"
                    },
                    "errors": {
                      "type": "object",
                      "properties": {
                        "role": {
                          "type": "array",
                          "items": {
                            "type": "string"
                          }
                        }
                      }
                    }
                  }
                },
                "example": {
                  "error": "The role field is required.",
                  "errors": {
                    "role": [
                      "The role field is required."
                    ]
                  }
                }
              }
            }
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "role": {
                    "type": "string"
                  }
                }
              },
              "example": {
                "role": "admin"
              }
            }
          }
        }
      }
    },
    "/auth/user": {
      "parameters": [],
      "get": {
        "tags": [
          "Auth"
        ],
        "summary": "Get Authenticated User",
        "parameters": [],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "integer"
                    },
                    "name": {
                      "type": "string"
                    },
                    "email": {
                      "type": "string",
                      "format": "email"
                    },
                    "active_role": {
                      "type": "string"
                    },
                    "roles": {
                      "type": "array",
                      "items": {
                        "type": "string"
                      }
                    },
                    "permissions": {
                      "type": "array",
                      "items": {
                        "type": "string"
                      }
                    }
                  }
                },
                "example": {
                  "id": 1,
                  "name": "Admin",
                  "email": "admin@example.com",
                  "active_role": "admin",
                  "roles": [
                    "admin",
                    "user"
                  ],
                  "permissions": [
                    "user.create",
                    "user.read",
                    "user.update",
                    "user.delete",
                    "user.assign.role",
                    "user.revoke.role",
                    "user.sync.role",
                    "country.create",
                    "country.read",
                    "country.update",
                    "country.delete",
                    "state.create",
                    "state.read",
                    "state.update",
                    "state.delete",
                    "city.create",
                    "city.read",
                    "city.update",
                    "city.delete"
                  ]
                }
              }
            }
          }
        }
      }
    },
    "/user/{user_id}/roles/assign": {
      "parameters": [],
      "post": {
        "tags": [
          "User Role"
        ],
        "summary": "Assign",
        "parameters": [],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "integer"
                    },
                    "name": {
                      "type": "string"
                    },
                    "email": {
                      "type": "string",
                      "format": "email"
                    },
                    "roles": {
                      "type": "array",
                      "items": {
                        "type": "string"
                      }
                    }
                  }
                },
                "example": {
                  "id": 1,
                  "name": "Admin",
                  "email": "admin@example.com",
                  "roles": [
                    "admin",
                    "user"
                  ]
                }
              }
            }
          },
          "422": {
            "description": "Unprocessable Content",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "string"
                    },
                    "errors": {
                      "type": "object",
                      "properties": {
                        "roles": {
                          "type": "array",
                          "items": {
                            "type": "string"
                          }
                        }
                      }
                    }
                  }
                },
                "example": {
                  "error": "The roles field is required.",
                  "errors": {
                    "roles": [
                      "The roles field is required."
                    ]
                  }
                }
              }
            }
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "roles": {
                    "type": "array",
                    "items": {
                      "type": "string"
                    }
                  }
                }
              },
              "example": {
                "roles": [
                  "admin",
                  "user"
                ]
              }
            }
          }
        }
      }
    },
    "/user/{user_id}/roles/revoke": {
      "parameters": [],
      "post": {
        "tags": [
          "User Role"
        ],
        "summary": "Revoke",
        "parameters": [],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "integer"
                    },
                    "name": {
                      "type": "string"
                    },
                    "email": {
                      "type": "string",
                      "format": "email"
                    },
                    "roles": {
                      "type": "array",
                      "items": {
                        "type": "string"
                      }
                    }
                  }
                },
                "example": {
                  "id": 1,
                  "name": "Admin",
                  "email": "admin@example.com",
                  "roles": [
                    "admin"
                  ]
                }
              }
            }
          },
          "422": {
            "description": "Unprocessable Content",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "string"
                    },
                    "errors": {
                      "type": "object",
                      "properties": {
                        "roles": {
                          "type": "array",
                          "items": {
                            "type": "string"
                          }
                        }
                      }
                    }
                  }
                },
                "example": {
                  "error": "The roles field is required.",
                  "errors": {
                    "roles": [
                      "The roles field is required."
                    ]
                  }
                }
              }
            }
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "roles": {
                    "type": "array",
                    "items": {
                      "type": "string"
                    }
                  }
                }
              },
              "example": {
                "roles": [
                  "user"
                ]
              }
            }
          }
        }
      }
    },
    "/user/{user_id}/roles/sync": {
      "parameters": [],
      "post": {
        "tags": [
          "User Role"
        ],
        "summary": "Sync",
        "parameters": [],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "integer"
                    },
                    "name": {
                      "type": "string"
                    },
                    "email": {
                      "type": "string",
                      "format": "email"
                    },
                    "roles": {
                      "type": "array",
                      "items": {
                        "type": "string"
                      }
                    }
                  }
                },
                "example": {
                  "id": 1,
                  "name": "Admin",
                  "email": "admin@example.com",
                  "roles": [
                    "admin",
                    "user"
                  ]
                }
              }
            }
          },
          "422": {
            "description": "Unprocessable Content",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "string"
                    },
                    "errors": {
                      "type": "object",
                      "properties": {
                        "roles": {
                          "type": "array",
                          "items": {
                            "type": "string"
                          }
                        }
                      }
                    }
                  }
                },
                "example": {
                  "error": "The roles field is required.",
                  "errors": {
                    "roles": [
                      "The roles field is required."
                    ]
                  }
                }
              }
            }
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "roles": {
                    "type": "array",
                    "items": {
                      "type": "string"
                    }
                  }
                }
              },
              "example": {
                "roles": [
                  "admin",
                  "user"
                ]
              }
            }
          }
        }
      }
    },
    "/user": {
      "parameters": [],
      "post": {
        "tags": [
          "User"
        ],
        "summary": "Create User",
        "parameters": [],
        "responses": {
          "201": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "integer"
                    },
                    "name": {
                      "type": "string"
                    },
                    "email": {
                      "type": "string",
                      "format": "email"
                    }
                  }
                },
                "example": {
                  "id": 4,
                  "name": "Teste 1",
                  "email": "teste@create.gmail.com"
                }
              }
            }
          },
          "422": {
            "description": "Unprocessable Content",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "string"
                    },
                    "errors": {
                      "type": "object",
                      "properties": {
                        "name": {
                          "type": "array",
                          "items": {
                            "type": "string"
                          }
                        },
                        "email": {
                          "type": "array",
                          "items": {
                            "type": "string"
                          }
                        },
                        "password": {
                          "type": "array",
                          "items": {
                            "type": "string"
                          }
                        }
                      }
                    }
                  }
                },
                "example": {
                  "error": "The name field is required. (and 2 more errors)",
                  "errors": {
                    "name": [
                      "The name field is required."
                    ],
                    "email": [
                      "The email field is required."
                    ],
                    "password": [
                      "The password field is required."
                    ]
                  }
                }
              }
            }
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string"
                  },
                  "email": {
                    "type": "string",
                    "format": "email"
                  },
                  "password": {
                    "type": "string"
                  },
                  "password_confirmation": {
                    "type": "string"
                  }
                }
              },
              "example": {
                "name": "Teste 1",
                "email": "teste@create.gmail.com",
                "password": "teste123",
                "password_confirmation": "teste123"
              }
            }
          }
        }
      },
      "get": {
        "tags": [
          "User"
        ],
        "summary": "Get All Users",
        "parameters": [
          {
            "name": "filter[id]",
            "in": "query",
            "required": false,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "filter[name]",
            "in": "query",
            "required": false,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "filter[email]",
            "in": "query",
            "required": false,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "filter[search]",
            "in": "query",
            "required": false,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "include",
            "in": "query",
            "required": false,
            "example": "roles,rolesCount,rolesExists",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "page[size]",
            "in": "query",
            "required": false,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "page[number]",
            "in": "query",
            "required": false,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "data": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "id": {
                            "type": "integer"
                          },
                          "name": {
                            "type": "string"
                          },
                          "email": {
                            "type": "string",
                            "format": "email"
                          }
                        }
                      }
                    },
                    "links": {
                      "type": "object",
                      "properties": {
                        "first": {
                          "type": "string",
                          "format": "uri"
                        },
                        "last": {
                          "type": "string",
                          "format": "uri"
                        },
                        "prev": {
                          "nullable": true
                        },
                        "next": {
                          "nullable": true
                        }
                      }
                    },
                    "meta": {
                      "type": "object",
                      "properties": {
                        "current_page": {
                          "type": "integer"
                        },
                        "from": {
                          "type": "integer"
                        },
                        "last_page": {
                          "type": "integer"
                        },
                        "links": {
                          "type": "array",
                          "items": {
                            "type": "object",
                            "properties": {
                              "url": {
                                "nullable": true
                              },
                              "label": {
                                "type": "string"
                              },
                              "page": {
                                "nullable": true
                              },
                              "active": {
                                "type": "boolean"
                              }
                            }
                          }
                        },
                        "path": {
                          "type": "string",
                          "format": "uri"
                        },
                        "per_page": {
                          "type": "integer"
                        },
                        "to": {
                          "type": "integer"
                        },
                        "total": {
                          "type": "integer"
                        }
                      }
                    }
                  }
                },
                "example": {
                  "data": [
                    {
                      "id": 1,
                      "name": "Admin",
                      "email": "admin@example.com"
                    },
                    {
                      "id": 2,
                      "name": "Teste",
                      "email": "teste@teste.gmail.com"
                    },
                    {
                      "id": 3,
                      "name": "Teste",
                      "email": "teste@teste1.gmail.com"
                    },
                    {
                      "id": 4,
                      "name": "Teste 1",
                      "email": "teste@create.gmail.com"
                    }
                  ],
                  "links": {
                    "first": "http://localhost:8000/api/v1/user?page%5Bnumber%5D=1",
                    "last": "http://localhost:8000/api/v1/user?page%5Bnumber%5D=1",
                    "prev": null,
                    "next": null
                  },
                  "meta": {
                    "current_page": 1,
                    "from": 1,
                    "last_page": 1,
                    "links": [
                      {
                        "url": null,
                        "label": "&laquo; Previous",
                        "page": null,
                        "active": false
                      },
                      {
                        "url": "http://localhost:8000/api/v1/user?page%5Bnumber%5D=1",
                        "label": "1",
                        "page": 1,
                        "active": true
                      },
                      {
                        "url": null,
                        "label": "Next &raquo;",
                        "page": null,
                        "active": false
                      }
                    ],
                    "path": "http://localhost:8000/api/v1/user",
                    "per_page": 10,
                    "to": 4,
                    "total": 4
                  }
                }
              }
            }
          }
        }
      }
    },
    "/user/{user_id}": {
      "parameters": [],
      "get": {
        "tags": [
          "User"
        ],
        "summary": "Get User by ID",
        "parameters": [
          {
            "name": "include",
            "in": "query",
            "required": false,
            "example": "roles,rolesCount,rolesExists",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "Accept",
            "in": "header",
            "required": false,
            "example": "application/json",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "integer"
                    },
                    "name": {
                      "type": "string"
                    },
                    "email": {
                      "type": "string",
                      "format": "email"
                    },
                    "roles": {
                      "type": "array",
                      "items": {
                        "type": "string"
                      }
                    },
                    "roles_count": {
                      "type": "integer"
                    },
                    "roles_exists": {
                      "type": "boolean"
                    }
                  }
                },
                "example": {
                  "id": 1,
                  "name": "Admin",
                  "email": "admin@example.com",
                  "roles": [
                    "admin",
                    "user"
                  ],
                  "roles_count": 2,
                  "roles_exists": true
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "string"
                    }
                  }
                },
                "example": {
                  "error": "The requested resource was not found."
                }
              }
            }
          }
        }
      },
      "put": {
        "tags": [
          "User"
        ],
        "summary": "Update User",
        "parameters": [],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "integer"
                    },
                    "name": {
                      "type": "string"
                    },
                    "email": {
                      "type": "string",
                      "format": "email"
                    }
                  }
                },
                "example": {
                  "id": 2,
                  "name": "Teste 1 Update",
                  "email": "teste@update.gmail.com"
                }
              }
            }
          },
          "422": {
            "description": "Unprocessable Content",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "string"
                    },
                    "errors": {
                      "type": "object",
                      "properties": {
                        "name": {
                          "type": "array",
                          "items": {
                            "type": "string"
                          }
                        },
                        "email": {
                          "type": "array",
                          "items": {
                            "type": "string"
                          }
                        }
                      }
                    }
                  }
                },
                "example": {
                  "error": "The name field is required. (and 1 more error)",
                  "errors": {
                    "name": [
                      "The name field is required."
                    ],
                    "email": [
                      "The email field is required."
                    ]
                  }
                }
              }
            }
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string"
                  },
                  "email": {
                    "type": "string",
                    "format": "email"
                  }
                }
              },
              "example": {
                "name": "Teste 1 Update",
                "email": "teste@update.gmail.com"
              }
            }
          }
        }
      },
      "delete": {
        "tags": [
          "User"
        ],
        "summary": "Delete User",
        "parameters": [],
        "responses": {
          "204": {
            "description": "No Content",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {}
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "string"
                    }
                  }
                },
                "example": {
                  "error": "The requested resource was not found."
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    }
  },
  "security": [
    {
      "bearerAuth": []
    }
  ]
}